name: webapp Security Scan

on:
  push:
    branches: [ main ]

jobs:
  Sandworm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
          
      - name: Install dependencies
        run: |
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
          | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
          echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] \
          https://deb.nodesource.com/node_20.x nodistro main" \
          | tee /etc/apt/sources.list.d/nodesource.list
          apt update
          apt install -y nodejs
          npm install
          npm install -g @sandworm/audit    
      
      - name: Run Sandworm Scanner (Markdown format)
        run: sandworm audit
        continue-on-error: true
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path:
            Sandworm/myapp@*-report.json
        if: always()

