name: Django Security Scan

on:
  push:
    branches: [ main ]

jobs:
  osv-scanner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          npm install
          go install github.com/google/osv-scanner/cmd/osv-scanner@v1
          
      - name: Run OSV Scanner (Markdown format)
        run: osv-scanner --format markdown . > osv-report.md
        continue-on-error: true
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path:
            osv-report.md
        if: always()

